FROM python:3.7

EXPOSE 8501
#ENV PORT=8501

RUN apt-get update && apt-get install -y gfortran libblas-dev liblapack-dev build-essential cmake texlive cm-super texlive-latex-extra dvipng

RUN git clone https://github.com/LLNL/sundials.git; \
    mkdir /sundials/build;\
    cd /sundials/build; \
    cmake -DLAPACK_ENABLE=ON ..; \
    make && make install

RUN apt-get install -y python3-dev python3-pip
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt
WORKDIR /app
COPY . .

CMD streamlit run --server.port $PORT app.py
